//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaMEntities : DbContext
    {
        public SaMEntities()
            : base("name=SaMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<T> Set<T>()
        {
            throw new NotImplementedException();
        }

        public object Entry<T>(T entity) where T : class
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<TaskLogs> TaskLogs { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
